import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <nav
          className="navbar bg-dark border-bottom border-body"
          data-bs-theme="dark"
        >
          <div className="container-fluid container">
            <a className="navbar-brand" href="/">
              Optimizador-IO
            </a>
            <ul className="navbar-nav d-flex flex-row">
              <li className="nav-item ms-4">
                <a
                  className="nav-link active"
                  aria-current="page"
                  href="/programacion-lineal"
                >
                  Programación Lineal
                </a>
              </li>
              <li className="nav-item ms-4">
                <a
                  className="nav-link active"
                  aria-current="page"
                  href="/transporte"
                >
                  Transporte
                </a>
              </li>
              <li className="nav-item ms-4">
                <a
                  className="nav-link active"
                  aria-current="page"
                  href="/grafos"
                >
                  Grafos
                </a>
              </li>
            </ul>
          </div>
        </nav>
        <main className="mt-2 container">{children}</main>
      </body>
    </html>
  );
}
